# Generated by Django 3.2.8 on 2024-04-21 17:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appUI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='title',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='user_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
