# Generated by Django 3.2.8 on 2024-04-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUI', '0002_auto_20240421_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
