# Generated by Django 3.2.8 on 2024-04-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUI', '0003_alter_uploadedimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
